---
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: :construction_worker: "
      include: scope

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore: :arrow_up: "
      include: scope
