# Basic set up for Cargo project

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "chore:"
      include: scope

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "deps:"
      include: scope
